var availableDrinks = ["Cherry Syrup",
	"Coco Lopez® Cream of Coconut",
	"Cold Milk",
	"Cranberry Liqueur",
	"Cranberry-Raspberry Juice",
	"D Banana",
	"Dry White Wine",
	"Fresh Cream",
	"Frozen Pink Lemonade",
	"Gosling's® Black Seal Rum",
	"Jim Beam Black Label Bourbon Whiskey",
	"Johnnie Walker® Black Label Scotch Whisky",
	"Kim Milk",
	"Kiwi Liqueur",
	"Lapponia Lakka Cloudberry Liqueur",
	"Mango Nectar",
	"Martini & Rossi® Dry Vermouth",
	"Mezcal",
	"Mint Schnapps",
	"Remy Martin® Cognac",
	"Rock and Rye® Liqueur",
	"Rum Tree® Liqueur",
	"Sherbet",
	"Sherry",
	"Skyy® Citrus Vodka",
	"Smirnoff® Blue Label Vodka",
	"Smirnoff® Watermelon Twist Vodka",
	"Sparkling White Wine",
	"Stoli® Persik Vodka",
	"Strawberry Juice",
	"Sweetened Lime Juice",
	"Zubrowka® Vodka",
	"99 Apples® Apple Schnapps",
	"Absolut® Vanilia Vodka",
	"Alize® Bleu Liqueur",
	"Bananas",
	"Batida De Coco",
	"Blackberry Liqueur",
	"Blackberry Schnapps",
	"Canadian Mist® Whisky",
	"Captain Morgan® Parrot Bay Pineapple Rum",
	"Chilled Ginger Ale",
	"Clamato Juice",
	"Coca-Cola® Cherry Coke",
	"Crushed Pineapples",
	"Dry Ginger Ale",
	"Fruits",
	"Gomme Syrup",
	"Grain Alcohol",
	"Grape Soda",
	"Hard Cider",
	"Horseradish",
	"Hot Tea",
	"Johnnie Walker® Red Label Scotch Whisky",
	"Light Beer",
	"Old Grandad® Bourbon Whiskey",
	"Pepper Vodka",
	"Raspberries",
	"Safari® Liqueur",
	"Stoli® Kafya Vodka",
	"Strongbow® Cider",
	"White Chocolate Liqueur",
	"Absolut® Apeach Vodka",
	"Alize® Gold Passion Liqueur",
	"Archers® Peach Schnapps",
	"Armagnac",
	"Bacardi® Big Apple Rum",
	"Bacardi® Black Rum",
	"Bacardi® Coco Rum",
	"Bacardi® Superior Rum",
	"Black Raspberry Liqueur",
	"Bols® Creme De Bananes",
	"Bushmills® Irish Whiskey",
	"Caramel Syrup",
	"Cherries",
	"Chilled Orange Juice",
	"Cocoa",
	"Collins Mix",
	"Corona® Lager",
	"Courvoisier® Cognac",
	"DeKuyper® Raspberry Pucker Schnapps",
	"Hot Cocoa",
	"Lass Orange Juice",
	"Lemon-Lime Mix",
	"Malibu® Pineapple Rum",
	"Mozart® Black Chocolate Liqueur",
	"Mozart® Original Chocolate Liqueur",
	"Orange Liqueur",
	"Orange Sherbet",
	"Overproof Rum",
	"Peach Vodka",
	"Pisco Brandy",
	"Ricard® Pastis",
	"Rockstar® Energy Drink",
	"Ruby Port",
	"Sauza® Hornitos Reposado Tequila",
	"Wildberry Schnapps",
	"Almond Syrup",
	"Blackcurrant Cordial",
	"Canadian Club® Whisky",
	"Captain Morgan® Silver Spiced Rum",
	"Captain Morgan® Tattoo Orange Rum",
	"Chilled Cola",
	"Coca-Cola® Vanilla Coke",
	"Corona® Extra Lager",
	"Dole® Pineapple Juice",
	"Fresh Grapefruit Juice",
	"Kummel® Caraway Liqueur",
	"Madeira",
	"Maker's Mark® Bourbon Whiskey",
	"Mango Rum",
	"Maraschino Cherries",
	"Plymouth® Gin",
	"Seagram's® Gin",
	"Smirnoff® Ice",
	"Smirnoff® Vanilla Twist Vodka",
	"Strawberry Margarita Mix",
	"Surge® Citrus Soda",
	"V8® Vegetable Juice",
	"100 Vodka",
	"Alize® Liqueur",
	"Amer Picon® Orange Bitters",
	"Apricot Nectar",
	"DeKuyper® Grape Pucker Schnapps",
	"Ginger Beer",
	"Lass Beer",
	"Lime Cordial",
	"Peach Juice",
	"Pear Liqueur",
	"Peychaud® Bitters",
	"Pineapple Syrup",
	"Raspberry Juice",
	"Schweppes® Russian Tonic Water",
	"White Grape Juice",
	"Absolut® Peppar Vodka",
	"Almond Extract",
	"Cream Sherry",
	"Fanta® Orange Soda",
	"French Vermouth",
	"Godiva® White Chocolate Liqueur",
	"LBV Port",
	"Oranges",
	"Papaya Juice",
	"Peppers",
	"Stolichnaya® Vanilla Vodka",
	"Strawberry Vodka",
	"Whisky",
	"Apple Vodka",
	"Bitter Lemon Soda",
	"Fresca® Grapefruit Soda",
	"Hershey's® Chocolate Syrup",
	"Jose Cuervo® Gold Tequila",
	"Kamora® Coffee Liqueur",
	"Ketel One® Vodka",
	"Pimm's® Gin",
	"Punt E Mes Red Vermouth",
	"Smirnoff® Raspberry Twist Vodka",
	"Tang® Powdered Soft Drink",
	"Bacardi® Dark Rum",
	"Calvados® Brandy",
	"Cherry Cola",
	"Chocolate",
	"Cider",
	"Dr. McGillicuddy Vanilla Schnapps",
	"Fernet Branca® Bitters",
	"Fruit Juice",
	"Hazelnut Liqueur",
	"Peach Nectar",
	"Pomegranate Juice",
	"Tawny Port",
	"UV® Blue Raspberry Vodka",
	"Absolut® Vanilla Vodka",
	"Barenjager® Honey Liqueur",
	"Cold Water",
	"Frozen Orange Juice",
	"Grated Nutmeg",
	"Limoncello Lemon Liqueur",
	"Monster® Energy Drink",
	"Pineapple Rum",
	"Pineapples",
	"RedRum® Rum",
	"Seagram's® 7 Whisky",
	"Absolut® Raspberri Vodka",
	"Coconut Liqueur",
	"DeKuyper® Cheri-Beri Pucker Schnapps",
	"Kool-Aid®",
	"Kool-Aid® Cherry Mix",
	"Lager",
	"Lime Vodka",
	"Soda",
	"Sour Puss® Raspberry Liqueur",
	"Stoli® Strasberi Vodka",
	"Amarula Cream Liqueur",
	"Captain Morgan® Parrot Bay Mango Rum",
	"Celery Salt",
	"Cocoa Powder",
	"Frozen Limeade",
	"Gatorade® Energy Drink",
	"Gordon's® Gin",
	"Lillet® Blanc Wine",
	"Ocean Spray® Cranberry Juice",
	"Sagatiba Pura",
	"Silver Tequila",
	"Strawberry Daiquiri Mix",
	"Strega® Herbal Liqueur",
	"White Curacao Liqueur",
	"Anis Liqueur",
	"Cherry Liqueur",
	"Creme De Almond",
	"Limeade",
	"Vanilla",
	"Vanilla Liqueur",
	"White Sambuca",
	"Bacardi® Razz Rum",
	"Chocolate Liqueur",
	"Guava Juice",
	"Heering® Cherry Liqueur",
	"Jose Cuervo® 1800 Tequila",
	"Pink Lemonade",
	"Tropicana® Orange Juice",
	"Wild Turkey® 101 Bourbon Whiskey",
	"Zima",
	"Carbonated Water",
	"Granulated Sugar",
	"Hot Water",
	"Parfait Amour® Orange Liqueur",
	"Rose's® Grenadine Syrup",
	"Smirnoff® Green Apple Twist Vodka",
	"Sparkling Bitter Lemon Soda",
	"Strawberry Puree",
	"Vermouth",
	"Brown Creme De Cacao",
	"Brown Sugar",
	"Chocolate Ice Cream",
	"Coffee Brandy",
	"Cold Coffee",
	"Dubonnet® French Vermouth",
	"Eggnog",
	"Pineapple",
	"Alize® Red Passion Liqueur",
	"Bacardi® Gold Rum",
	"Citrus Vodka",
	"Ice Cream",
	"Iced Tea",
	"Johnnie Walker® Scotch Whisky",
	"Port",
	"Aquavit",
	"Chilled Champagne",
	"Coconut Milk",
	"Espresso",
	"Margarita Mix",
	"Raspberry Syrup",
	"Strawberry Syrup",
	"Bacardi® O Rum",
	"Lemons",
	"Tuaca® Citrus Liqueur",
	"DeKuyper® Island Blue Pucker Schnapps",
	"Instant Coffee",
	"Irish Mist® Herbal Liqueur",
	"Passion-Fruit Syrup",
	"Dry Gin",
	"Ground Cinnamon",
	"Limes",
	"Malibu® Mango Rum",
	"Strawberries",
	"White Wine",
	"Advocaat Liqueur",
	"Firewater® Cinnamon Schnapps",
	"Ouzo Anise Liqueur",
	"Apple Cider",
	"Finlandia® Vodka",
	"Frozen Lemonade",
	"Jameson® Irish Whiskey",
	"Rye Whiskey",
	"Beefeater® Gin",
	"Cream Soda",
	"Licor 43® Liqueur",
	"Maple Syrup",
	"Orgeat Syrup",
	"Sake Rice Wine",
	"Vanilla Schnapps",
	"Orange Vodka",
	"Raspberry Schnapps",
	"Squirt® Citrus Soda",
	"Curacao Orange Liqueur",
	"Dubonnet® Rouge Vermouth",
	"Fruit Punch",
	"Worcestershire Sauce",
	"Bacardi® Orange Rum",
	"Creme De Noyaux",
	"DeKuyper® Razzmatazz Liqueur",
	"Egg",
	"Red Wine",
	"Sunny Delight® Orange Juice",
	"Watermelon Schnapps",
	"Yellow Chartreuse®",
	"Anejo Rum",
	"Applejack® Brandy",
	"Can Red Bull® Energy Drink",
	"Caster Sugar",
	"Chocolate Milk",
	"Cream of Coconut",
	"Sweet Sherry",
	"Hawaiian Punch®",
	"Pina Colada Mix",
	"Jamaican Dark Rum",
	"Peach Brandy",
	"Stoli® Ohranj Vodka",
	"Blueberry Schnapps",
	"Grape Juice",
	"Lemon Vodka",
	"Orange Soda",
	"Passoa® Liqueur",
	"Black Sambuca",
	"Cherry Vodka",
	"Pepsi® Cola",
	"Root Beer",
	"Strawberry Schnapps",
	"Black Haus® Blackberry Schnapps",
	"Cherry Juice",
	"Myer's® Dark Rum",
	"Rosso Vermouth",
	"Kirschwasser® Cherry Brandy",
	"Maui® Blue Hawaiian Schnapps",
	"Bacardi® Light Rum",
	"Bombay Sapphire® Gin",
	"Creme De Menthe",
	"Dry Sherry",
	"Tomato Juice",
	"Stoli® Razberi Vodka",
	"Double Cream",
	"Mandarine Napoleon® Orange Liqueur",
	"Mango Juice",
	"Root Beer Schnapps",
	"Tequila Rose® Strawberry Cream Liqueur",
	"Guinness® Stout",
	"Raspberry Vodka",
	"Mandarin Juice",
	"99 Bananas® Banana Schnapps",
	"Anisette",
	"Hot Chocolate",
	"Strawberry Liqueur",
	"Vanilla Extract",
	"Boiling Water",
	"DeKuyper® Watermelon Pucker Schnapps",
	"Hennessy® Cognac",
	"Nutmeg",
	"Orange Curacao Liqueur",
	"Skyy® Vodka",
	"Absolut® Kurant Vodka",
	"Tanqueray® Gin",
	"DeKuyper® Hot Damn Cinnamon Schnapps",
	"Gold Rum",
	"Lime",
	"Apple Brandy",
	"Godiva® Chocolate Liqueur",
	"Pisang Ambon® Liqueur",
	"Cinnamon",
	"Green Chartreuse®",
	"Absolut® Mandrin Vodka",
	"Grey Goose® Vodka",
	"Cinnamon Schnapps",
	"Coffee",
	"Simple Syrup",
	"Orange",
	"Absinthe Herbal Liqueur",
	"Honey",
	"DeKuyper® Buttershots Liqueur",
	"Stoli® Vanil Vodka",
	"Apple Schnapps",
	"Blended Whiskey",
	"Passion-Fruit Juice",
	"DeKuyper® Peachtree Schnapps",
	"Whipping Cream",
	"Amaretto Di Saronno® Liqueur",
	"Irish Whiskey",
	"Stolichnaya® Vodka",
	"Aftershock® Hot & Cool Cinnamon Schnapps",
	"Fresh Orange Juice",
	"Lemon-Lime Soda",
	"Salt",
	"Raspberry Liqueur",
	"Wild Turkey® Bourbon Whiskey",
	"Yukon Jack® Canadian Whisky",
	"Benedictine Herbal Liqueur",
	"Vanilla Vodka",
	"Hot Coffee",
	"Chocolate Syrup",
	"Coffee Liqueur",
	"Coconut Cream",
	"Drambuie® Scotch Whisky",
	"Blackberry Brandy",
	"Cola",
	"Tia Maria® Coffee Liqueur",
	"Tonic Water",
	"White Tequila",
	"Captain Morgan® Parrot Bay Coconut Rum",
	"Canadian Whisky",
	"Captain Morgan® Spiced Rum",
	"Heavy Cream",
	"Creme De Cassis",
	"Spiced Rum",
	"Dr. Pepper® Soda",
	"Powdered Sugar",
	"Gold Tequila",
	"Light Cream",
	"Crushed Ice",
	"Pernod® Licorice Liqueur",
	"Sambuca",
	"Ice Cubes",
	"Superfine Sugar",
	"Whiskey",
	"Maraschino Liqueur",
	"Smirnoff® Vodka",
	"White Creme De Menthe",
	"Bacardi® Limon Rum",
	"Campari® Bitters",
	"Green Creme De Menthe",
	"Irish Cream",
	"Absolut® Citron Vodka",
	"Half-And-Half",
	"Apple Juice",
	"Beer",
	"Fresh Lemon Juice",
	"Orange Bitters",
	"Hpnotiq® Liqueur",
	"Jose Cuervo® Especial Gold Tequila",
	"Sloe Gin",
	"Rumple Minze® Peppermint Liqueur",
	"Bacardi® White Rum",
	"Sugar Syrup",
	"Fresh Lime Juice",
	"Creme De Cacao",
	"Jim Beam® Bourbon Whiskey",
	"Soda Water",
	"Mountain Dew® Citrus Soda",
	"Tabasco® Sauce",
	"Water",
	"Cognac",
	"Dark Creme De Cacao",
	"Angostura® Bitters",
	"Peppermint Schnapps",
	"Creme De Bananes",
	"Galliano® Herbal Liqueur",
	"Captain Morgan® Original Spiced Rum",
	"DeKuyper® Sour Apple Pucker Schnapps",
	"151 Proof Rum",
	"Vanilla Ice Cream",
	"Lemon",
	"Crown Royal® Canadian Whisky",
	"Rose's® Lime Juice",
	"Bitters",
	"Red Bull® Energy Drink",
	"Champagne",
	"Cherry Brandy",
	"Melon Liqueur",
	"Coconut Rum",
	"Apricot Brandy",
	"Bourbon Whiskey",
	"Everclear® Alcohol",
	"Butterscotch Schnapps",
	"Whipped Cream",
	"Club Soda",
	"Scotch Whisky",
	"Banana Liqueur",
	"Frangelico® Hazelnut Liqueur",
	"Grapefruit Juice",
	"Sweet Vermouth",
	"Goldschlager® Cinnamon Schnapps",
	"Ice",
	"Grand Marnier® Orange Liqueur",
	"White Creme De Cacao",
	"Chambord® Raspberry Liqueur",
	"Coca-Cola®",
	"Ginger Ale",
	"Absolut® Vodka",
	"White Rum",
	"Rum",
	"Lemonade",
	"Jack Daniel's® Tennessee Whiskey",
	"Cream",
	"Bacardi® 151 Rum",
	"Cointreau® Orange Liqueur",
	"Sugar",
	"Dark Rum",
	"Light Rum",
	"Brandy",
	"Sprite® Soda",
	"Milk",
	"Dry Vermouth",
	"Jagermeister® Herbal Liqueur",
	"7-Up® Soda",
	"Midori® Melon Liqueur",
	"Tequila",
	"Southern Comfort® Peach Liqueur",
	"Malibu® Coconut Rum",
	"Peach Schnapps",
	"Lime Juice",
	"Blue Curacao Liqueur",
	"Sweet and Sour Mix",
	"Kahlua® Coffee Liqueur",
	"Bailey's® Irish Cream",
	"Amaretto Almond Liqueur",
	"Lemon Juice",
	"Cranberry Juice",
	"Triple Sec",
	"Gin",
	"Grenadine Syrup",
	"Pineapple Juice",
	"Orange Juice",
	"Vodka"];