allIngredients = ["100 Absolut® Vodka",
    "100 Cinnamon Schnapps",
    "100 Proof Vodka",
    "100 Smirnoff® Vodka",
    "100 Southern Comfort® Peach Liqueur",
    "100 Vodka",
    "100% Cranberry Juice",
    "151 Proof Rum",
    "1800® Silver Tequila",
    "1800Ž Reposado Tequila",
    "190 Everclear® Alcohol",
    "2% Milk",
    "42 Below® Vodka",
    "7-Up Plus Soda",
    "7-Up® Cherry Soda",
    "7-Up® Diet Soda",
    "7-Up® Soda",
    "99 Apples® Apple Schnapps",
    "99 Bananas® Banana Schnapps",
    "99 Blackberries® Blackberry Schnapps",
    "99 Oranges® Orange Schnapps",
    "A&W® Cream Soda",
    "A&W® Root Beer",
    "Absinthe Herbal Liqueur",
    "Absinth® Absinthe Herbal Liqueur",
    "Absolut® Apeach Vodka",
    "Absolut® Citron Vodka",
    "Absolut® Kurant Vodka",
    "Absolut® Mandrin Vodka",
    "Absolut® Peach Vodka",
    "Absolut® Pears Vodka",
    "Absolut® Peppar Vodka",
    "Absolut® Raspberri Vodka",
    "Absolut® Ruby Red Vodka",
    "Absolut® Vanilia Vodka",
    "Absolut® Vanilla Vodka",
    "Absolut® Vodka",
    "Admiral Nelson® Spiced Rum",
    "Advocaat Liqueur",
    "Aftershock® Cool Citrus Mint Schnapps",
    "Aftershock® Hot & Cool Cinnamon Schnapps",
    "Aftershock® Thermal Bite Spice Schnapps",
    "Agavero® Tequila Liqueur",
    "Aged Tequila",
    "Alcohol",
    "Ale",
    "Alize® Bleu Liqueur",
    "Alize® Cognac",
    "Alize® Gold Passion Liqueur",
    "Alize® Liqueur",
    "Alize® Red Passion Liqueur",
    "Allspice",
    "Almond Extract",
    "Almond Syrup",
    "Almond Tea",
    "Amadeus® Almond Liqueur",
    "Amaretto Almond Liqueur",
    "Amaretto Di Amore® Liqueur",
    "Amaretto Di Saronno® Liqueur",
    "Amarula Cream Liqueur",
    "Amber Rum",
    "Amer Picon® Orange Bitters",
    "Amontillado® Dry Sherry",
    "Amp® Energy Drink",
    "Anejo Rum",
    "Angostura® Bitters",
    "Anis Liqueur",
    "Anisette",
    "Aperol® Orange Liqueur",
    "Apfelkorn Liqueur",
    "Apple",
    "Apple Brandy",
    "Apple Cider",
    "Apple Juice",
    "Apple Liqueur",
    "Apple Rum",
    "Apple Sauce",
    "Apple Schnapps",
    "Apple Vodka",
    "Applejack® Brandy",
    "Appleton Estate® Dark Jamaica Rum",
    "Apricot",
    "Apricot Brandy",
    "Apricot Brandy Liqueur",
    "Apricot Juice",
    "Apricot Liqueur",
    "Apricot Nectar",
    "Aquavit",
    "Arak",
    "Archers® Peach Schnapps",
    "Aristocrat® Vodka",
    "AriZona® Iced Tea",
    "Armagnac",
    "Arnish Lime",
    "Arrow® Peach Schnapps",
    "Arrow® Peppermint Schnapps",
    "Avalanche® Peppermint Schnapps",
    "B & B® Benedictine",
    "Bacardi Breezer® Orange",
    "Bacardi® 151 Rum",
    "Bacardi® Apple Rum",
    "Bacardi® Big Apple Rum",
    "Bacardi® Black Rum",
    "Bacardi® Ciclon Gold Rum",
    "Bacardi® Coco Rum",
    "Bacardi® Dark Rum",
    "Bacardi® Gold Rum",
    "Bacardi® Light Rum",
    "Bacardi® Limon Rum",
    "Bacardi® O Rum",
    "Bacardi® Orange Rum",
    "Bacardi® Peach Red Rum",
    "Bacardi® Razz Rum",
    "Bacardi® Select Rum",
    "Bacardi® Silver O3",
    "Bacardi® Silver Rum",
    "Bacardi® Spiced Rum",
    "Bacardi® Superior Rum",
    "Bacardi® Tropico Rum",
    "Bacardi® Vanil Rum",
    "Bacardi® Vanilla Rum",
    "Bacardi® White Rum",
    "Bailey's® Caramel Irish Cream Liqueur",
    "Bailey's® Irish Cream",
    "Baja Luna® Black Raspberry Liqueur",
    "Baja Rosa® Strawberry Cream Liqueur",
    "Banana",
    "Banana Juice",
    "Banana Liqueur",
    "Banana Rum",
    "Banana Schnapps",
    "Banana Syrup",
    "Bananas",
    "Banker's Club® Vodka",
    "Barbados Dark Rum",
    "Barenfang® Honey Liqueur",
    "Barenjager® Honey Liqueur",
    "Bartons® Vodka",
    "Bass® Pale Ale",
    "Batida De Coco",
    "Battery® Energy Drink",
    "Bawls® Energy Drink",
    "Becherovka® Herbal Liqueur",
    "Beef Bouillon",
    "Beefeater® Gin",
    "Beer",
    "Belvedere® Vodka",
    "Benedictine Herbal Liqueur",
    "Berentzen's® Apple Liqueur",
    "Berries",
    "Bianco Vermouth",
    "Birch Beer",
    "Bitter Lemon Soda",
    "Bitters",
    "Black Coffee",
    "Black Haus® Blackberry Schnapps",
    "Black Peppers",
    "Black Raspberry Liqueur",
    "Black Rum",
    "Black Sambuca",
    "Black Tea",
    "Black Velvet® Canadian Whisky",
    "Blackberries",
    "Blackberry Brandy",
    "Blackberry Liqueur",
    "Blackberry Schnapps",
    "Blackcurrant Cordial",
    "Blackcurrant Juice",
    "Blackcurrant Squash",
    "Blackcurrant Syrup",
    "Blackcurrant Vodka",
    "Blavod® Vodka",
    "Blended Whiskey",
    "Blood Orange Juice",
    "Blood-Orange Juice",
    "Blue Curacao Liqueur",
    "Blue Food Coloring",
    "Blue Moon® Belgian Ale",
    "Blue Tattoo® Blueberry Schnapps",
    "Blueberries",
    "Blueberry Brandy",
    "Blueberry Juice",
    "Blueberry Liqueur",
    "Blueberry Schnapps",
    "Blueberry Syrup",
    "Blueberry Vodka",
    "Boiling Water",
    "Bols® Advocaat Liqueur",
    "Bols® Apricot Brandy",
    "Bols® Blue Curacao Liqueur",
    "Bols® Cherry Brandy",
    "Bols® Creme De Bananes",
    "Bols® Kiwi Liqueur",
    "Bols® Orange Curacao Liqueur",
    "Bols® Triple Sec",
    "Bols® White Creme De Cacao",
    "Bombay Sapphire® Gin",
    "Bottle Corona® Lager",
    "Bottle Everclear® Alcohol",
    "Bottle Rum",
    "Bottle Sprite® Soda",
    "Bottle Vodka",
    "Bourbon Whiskey",
    "Brandy",
    "Brown Creme De Cacao",
    "Brown Sugar",
    "Brown Sugar Syrup",
    "Brut® Champagne",
    "Bud Light® Lager",
    "Budweiser® Lager",
    "Bulmers® Cider",
    "Bundaberg® Amber Rum",
    "Bundaberg® Dark Rum",
    "Burgundy Wine",
    "Bushmills® Irish Cream",
    "Bushmills® Irish Whiskey",
    "Butter",
    "Butter Milk",
    "Butterscotch Liqueur",
    "Butterscotch Schnapps",
    "Byrrh Wine",
    "Cabana Boy® Pineapple Coconut Rum",
    "Cabernet Sauvignon Red Wine",
    "Cabo Wabo® Anejo Tequila",
    "Cactus Cooler® Orange-Pineapple Soda",
    "Calvados® Brandy",
    "Campari® Bitters",
    "Can Dr. Pepper® Soda",
    "Can Fruit Cocktail",
    "Can Grapefruit Juice",
    "Can Lemonade",
    "Can Mountain Dew® Citrus Soda",
    "Can Orange Juice",
    "Can Pineapple Juice",
    "Can Red Bull® Energy Drink",
    "Can, Red Bull® Energy Drink",
    "Canada Dry® Ginger Ale",
    "Canadian Beer",
    "Canadian Club® Whisky",
    "Canadian Mist® Whisky",
    "Canadian Whisky",
    "Candies",
    "Candy",
    "Canned Pineapple Juice",
    "Canned Pineapples",
    "Cape Velvet® Cream Liqueur",
    "Cappuccino",
    "Captain Morgan® Coconut Rum",
    "Captain Morgan® Original Spiced Rum",
    "Captain Morgan® Parrot Bay Coconut Rum",
    "Captain Morgan® Parrot Bay Mango Rum",
    "Captain Morgan® Parrot Bay Pineapple Rum",
    "Captain Morgan® Private Stock Dark Rum",
    "Captain Morgan® Silver Spiced Rum",
    "Captain Morgan® Spiced Rum",
    "Captain Morgan® Tattoo Orange Rum",
    "Caramel Liqueur",
    "Caramel Sauce",
    "Caramel Syrup",
    "Carbonated Water",
    "Cardamom",
    "Carling® Lager",
    "Carolans® Irish Cream",
    "Carrot Juice",
    "Casa Noble® Reposado Tequila",
    "Caster Sugar",
    "Cayenne Peppers",
    "Cazadores® Tequila",
    "Celery Salt",
    "Chablis® White Wine",
    "Chambord® Raspberry Liqueur",
    "Chamomile Tea",
    "Champagne",
    "Charleston Follies® Liqueur",
    "Chartreuse® Herbal Liqueur",
    "Chateau Monet® Framboise Raspberry Liqueur",
    "Cheap Vodka",
    "Cherries",
    "Cherry Advocaat Liqueur",
    "Cherry Brandy",
    "Cherry Cider",
    "Cherry Cola",
    "Cherry Jell-O",
    "Cherry Jello",
    "Cherry Juice",
    "Cherry Liqueur",
    "Cherry Soda",
    "Cherry Syrup",
    "Cherry Vodka",
    "Cherry Whiskey",
    "Cherryade",
    "Chilled 7-Up® Soda",
    "Chilled Ale",
    "Chilled Apple Juice",
    "Chilled Champagne",
    "Chilled Chocolate Milk",
    "Chilled Club Soda",
    "Chilled Coca-Cola®",
    "Chilled Coffee",
    "Chilled Cola",
    "Chilled Cranberry Juice",
    "Chilled Espresso",
    "Chilled Fanta® Orange Soda",
    "Chilled Gatorade® Energy Drink",
    "Chilled Ginger Ale",
    "Chilled Ginger Beer",
    "Chilled Guinness® Stout",
    "Chilled Hpnotiq® Liqueur",
    "Chilled Jagermeister® Herbal Liqueur",
    "Chilled Jim Beam® Bourbon Whiskey",
    "Chilled Lemonade",
    "Chilled Milk",
    "Chilled Mountain Dew® Code Red Soda",
    "Chilled Orange Juice",
    "Chilled Pineapple Juice",
    "Chilled Red Bull® Energy Drink",
    "Chilled Soda Water",
    "Chilled Sprite® Soda",
    "Chilled Tequila Rose® Strawberry Cream Liqueur",
    "Chilled Vodka",
    "Chiquita Kiwi-Strawberry Juice",
    "Chivas Regal® Scotch Whisky",
    "Chocolate",
    "Chocolate Extract",
    "Chocolate Ice Cream",
    "Chocolate Liqueur",
    "Chocolate Milk",
    "Chocolate Mint Liqueur",
    "Chocolate Powder",
    "Chocolate Sauce",
    "Chocolate Syrup",
    "Chocolate Vodka",
    "Chopped Ice",
    "Chopped Melons",
    "Christian Brothers® Frost White Brandy",
    "Cider",
    "Cinnamon",
    "Cinnamon Schnapps",
    "Cinzano® Dry Vermouth",
    "Cinzano® Orancio French Vermouth",
    "Cinzano® Sweet Vermouth",
    "Citrus Vodka",
    "Clam Juice",
    "Clamato Juice",
    "Clan MacGregor Scotch Whisky",
    "Claret",
    "Clear Honey",
    "Cloves",
    "Club Soda",
    "Coca-Cola®",
    "Coca-Cola® Cherry Coke",
    "Coca-Cola® Diet Coke",
    "Coca-Cola® Diet Lime Coke",
    "Coca-Cola® Vanilla Coke",
    "Coco Lopez® Cream of Coconut",
    "Cocoa",
    "Cocoa Powder",
    "Coconut Cream",
    "Coconut Extract",
    "Coconut Ice Cream",
    "Coconut Liqueur",
    "Coconut Milk",
    "Coconut Rum",
    "Coconut Syrup",
    "Coconut Vodka",
    "CocoRibe® Coconut Rum",
    "Coffee",
    "Coffee Brandy",
    "Coffee Ice Cream",
    "Coffee Liqueur",
    "Cognac",
    "Cointreau® Orange Liqueur",
    "Cola",
    "Cold 7-Up® Soda",
    "Cold Coffee",
    "Cold Cola",
    "Cold Espresso",
    "Cold Milk",
    "Cold Tea",
    "Cold Water",
    "Collins Mix",
    "Concentrated Orange Juice",
    "Condensed Milk",
    "Coors® Light Beer",
    "Coriander",
    "Corona® Extra Lager",
    "Corona® Lager",
    "Countrytime® Pink Lemonade",
    "Countrytime® Yellow Lemonade",
    "Courvoisier® Cognac",
    "Cracked Ice",
    "Cranberries",
    "Cranberry",
    "Cranberry Juice",
    "Cranberry Liqueur",
    "Cranberry Soda",
    "Cranberry Vodka",
    "Cranberry-Apple Juice",
    "Cranberry-Grape Juice",
    "Cranberry-Raspberry Juice",
    "Cream",
    "Cream Cheese",
    "Cream of Coconut",
    "Cream Sherry",
    "Cream Soda",
    "Creamy Peanut Butter",
    "Creme De Almond",
    "Creme De Bananes",
    "Creme De Cacao",
    "Creme De Cassis",
    "Creme De Coconut",
    "Creme De Framboise",
    "Creme De Menthe",
    "Creme De Mure",
    "Creme De Myrtille",
    "Creme De Noyaux",
    "Creme De Violette",
    "Crown Royal® Canadian Whisky",
    "Crushed Ice",
    "Crushed Pineapples",
    "Cruzan® Banana Rum",
    "Cruzan® Coconut Rum",
    "Cruzan® Mango Rum",
    "Cruzan® Pineapple Rum",
    "Crystal Light® Lemonade Mix",
    "Crystal Light® Sunrise Classic Orange Mix",
    "Cucumber",
    "Curacao Orange Liqueur",
    "Cutty Sark® Scotch Whisky",
    "Cynar® Artichoke Liqueur",
    "D Apple",
    "D Apples",
    "D Banana",
    "D Bananas",
    "D Lemon",
    "D Orange",
    "D Oranges",
    "D Peach",
    "Daiquiri Mix",
    "Damiana® Herbal Liqueur",
    "Danzig Goldwasser® Orange Liqueur",
    "Dark Creme De Cacao",
    "Dark Rum",
    "DeKuyper Sour Apple Schnapps",
    "DeKuyper® Amaretto Almond Liqueur",
    "DeKuyper® Apple Barrel Schnapps",
    "DeKuyper® Blue Curacao Liqueur",
    "DeKuyper® Bluesberry Schnapps",
    "DeKuyper® Buttershots Liqueur",
    "DeKuyper® Cactus Juice Schnapps",
    "DeKuyper® Cheri-Beri Pucker Schnapps",
    "DeKuyper® Cinnamon Schnapps",
    "DeKuyper® Creme De Bananes",
    "DeKuyper® Dark Creme De Cacao",
    "DeKuyper® Grape Pucker Schnapps",
    "DeKuyper® Hot Damn 100 Cinnamon Schnapps",
    "DeKuyper® Hot Damn Cinnamon Schnapps",
    "DeKuyper® Island Blue Pucker Schnapps",
    "DeKuyper® Key Largo Schnapps",
    "DeKuyper® Mad Melon Schnapps",
    "DeKuyper® Peachtree Schnapps",
    "DeKuyper® Raspberry Pucker Schnapps",
    "DeKuyper® Razzmatazz Liqueur",
    "DeKuyper® Sour Apple Pucker Schnapps",
    "DeKuyper® Sour Peach Pucker Schnapps",
    "DeKuyper® Triple Sec",
    "DeKuyper® Watermelon Pucker Schnapps",
    "Del Monte® Pineapple Juice",
    "Deva® Absinthe",
    "Devil Springs® Vodka",
    "Dewar's® Scotch Whisky",
    "Dole Pine-Orange-Banana Juice",
    "Dole Pineapple",
    "Dole® Orange Juice",
    "Dole® Pineapple Juice",
    "Dom Perignon® Champagne",
    "Don Julio® Blanco Tequila",
    "Dooley's Original Toffee & Vodka",
    "Double Cream",
    "Dr. McGillicuddy Mentholmint Schnapps",
    "Dr. McGillicuddy Peach Schnapps",
    "Dr. McGillicuddy Vanilla Schnapps",
    "Dr. McGillicuddy's® Fireball Canadian Whisky",
    "Dr. Pepper® Soda",
    "Drambuie® Scotch Whisky",
    "Dried Orange",
    "Dry Cider",
    "Dry Gin",
    "Dry Ginger Ale",
    "Dry Orange Curacao Liqueur",
    "Dry Sherry",
    "Dry Sparkling Wine",
    "Dry Vermouth",
    "Dry White Wine",
    "Dubonnet® Blanc Vermouth",
    "Dubonnet® French Vermouth",
    "Dubonnet® Rouge Vermouth",
    "E&J® Brandy",
    "Ed Pineapple",
    "Egg",
    "Eggnog",
    "Eggs",
    "El Tesoro® Anejo Tequila",
    "Energy Soda",
    "Es Chocolate",
    "Es Cinnamon",
    "Es Sugar",
    "Espresso",
    "Evan Williams® Bourbon Whiskey",
    "Evaporated Milk",
    "Everclear® Alcohol",
    "Everglo Liqueur",
    "Extra Dry Vermouth",
    "Famous Grouse® Scotch Whisky",
    "Fanta® Orange Soda",
    "Farris® Soda Water",
    "Fernet Branca® Bitters",
    "Filtered Orange Juice",
    "Finlandia® Cranberry Vodka",
    "Finlandia® Lime Vodka",
    "Finlandia® Vodka",
    "Fino Sherry",
    "Firewater® Cinnamon Schnapps",
    "Five Alive® Fruit Juice",
    "Food Coloring",
    "Forbidden Fruit® Liqueur",
    "Foster's® Lager",
    "Four Roses® Bourbon Whiskey",
    "Framboise Raspberry Liqueur",
    "Frangelico® Hazelnut Liqueur",
    "French Kiss® Vanilla Liqueur",
    "French Vanilla Ice Cream",
    "French Vermouth",
    "Fresca® Black Cherry Soda",
    "Fresca® Citrus Soda",
    "Fresca® Grapefruit Soda",
    "Fresca® Lemon-Lime Soda",
    "Fresca® Peach Soda",
    "Fresh Cream",
    "Fresh Ginger",
    "Fresh Grapefruit Juice",
    "Fresh Lemon Juice",
    "Fresh Lime Juice",
    "Fresh Mangos",
    "Fresh Meyer Lemon Juice",
    "Fresh Orange Juice",
    "Fresh Peaches",
    "Fresh Pineapple Juice",
    "Fresh Pineapples",
    "Fresh Pomegranate Juice",
    "Fresh Strawberries",
    "Fresh, Espresso",
    "Freshly Key Lime Juice",
    "Freshly Lime Juice",
    "Freshly Orange Juice",
    "Fris® Vodka",
    "Frozen Apple Juice",
    "Frozen Berries",
    "Frozen Fruit Juice",
    "Frozen Fruit Punch",
    "Frozen Lemonade",
    "Frozen Lime Juice",
    "Frozen Limeade",
    "Frozen Orange Juice",
    "Frozen Peaches",
    "Frozen Pineapple",
    "Frozen Pink Lemonade",
    "Frozen Raspberries",
    "Frozen Strawberries",
    "Fruit",
    "Fruit Juice",
    "Fruit Punch",
    "Fruitopia® Fruit Juice",
    "Fruits",
    "Full Throttle® Energy Drink",
    "Galliano® Herbal Liqueur",
    "Galliano® White Sambuca",
    "Gatorade® Cool Blue Raspberry Energy Drink",
    "Gatorade® Energy Drink",
    "Gatorade® Fierce Melon Energy Drink",
    "Gatorade® Glacier Freeze Energy Drink",
    "Gatorade® Lemon-Lime Energy Drink",
    "Gatorade® Orange Soda",
    "Genever Gin",
    "Gentleman Jack® Bourbon Whiskey",
    "George Dickel® Tennessee Whiskey",
    "Georgia Moon® Corn Whiskey",
    "Gilbey's® Gin",
    "Gin",
    "Ginger",
    "Ginger Ale",
    "Ginger Beer",
    "Ginger Brandy",
    "Ginger Wine",
    "Glayva® Scotch Liqueur",
    "Glenfiddich® Scotch Whisky",
    "Glycerine",
    "Godet® White Chocolate Liqueur",
    "Godiva® Chocolate Liqueur",
    "Godiva® White Chocolate Liqueur",
    "Gold Rum",
    "Gold Tequila",
    "Golden Grain® Alcohol",
    "Goldenbarr® Chocolate Vodka",
    "Goldschlager® Cinnamon Schnapps",
    "Gomme Syrup",
    "Gordon's® Gin",
    "Gordon's® Vodka",
    "Gosling's® Black Seal Rum",
    "Grain Alcohol",
    "Grand Marnier® Orange Liqueur",
    "Granulated Sugar",
    "Grape Jello",
    "Grape Juice",
    "Grape Soda",
    "Grapefruit Juice",
    "Grapefruit Soda",
    "Grappa Brandy",
    "Grated Nutmeg",
    "Green Apple Vodka",
    "Green Chartreuse®",
    "Green Creme De Menthe",
    "Green Curacao Liqueur",
    "Green Food Coloring",
    "Green Gatorade® Energy Drink",
    "Green Ginger Wine",
    "Green Hawaiian Punch®",
    "Grenadine Syrup",
    "Grey Goose® L'Orange Vodka",
    "Grey Goose® Le Citron Vodka",
    "Grey Goose® Vanilla Vodka",
    "Grey Goose® Vodka",
    "Ground Allspice",
    "Ground Cinnamon",
    "Ground Cloves",
    "Ground Coffee",
    "Ground Ginger",
    "Ground Nutmeg",
    "Guava Juice",
    "Guava Nectar",
    "Guava Syrup",
    "Guavaberry Liqueur",
    "Guinness® Stout",
    "Habanero Pepper Sauce",
    "Half-And-Half",
    "Hard Cider",
    "Harp® Lager",
    "Harveys® Bristol Cream Sherry",
    "Havana Club® 7 Years Rum",
    "Havana Club® Anejo Reserva Rum",
    "Havana Club® White Rum",
    "Hawaiian Punch®",
    "Hawaiian Punch® Green Berry Rush",
    "Hazelnut Liqueur",
    "Heaven Hill® Bourbon Whiskey",
    "Heavy Cream",
    "Heavy Whipping Cream",
    "Heering® Cherry Liqueur",
    "Heineken® Lager",
    "Hennessey Cognac",
    "Hennessy® Cognac",
    "Henry McKenna® Bourbon Whiskey",
    "Hershey's® Caramel Syrup",
    "Hershey's® Chocolate Syrup",
    "High Vodka",
    "Hiram Walker® Blue Curacao Liqueur",
    "Honey",
    "Honey Syrup",
    "Honey Vodka",
    "Hooper's® Hooch",
    "Horchata",
    "Hornsby's Draft® Cider",
    "Horseradish",
    "Hot Apple Cider",
    "Hot Chocolate",
    "Hot Cocoa",
    "Hot Coffee",
    "Hot Espresso",
    "Hot Milk",
    "Hot Pepper Sauce",
    "Hot Tea",
    "Hot Water",
    "Hot, Coffee",
    "Hpnotiq® Liqueur",
    "IBC® Root Beer",
    "Ice",
    "Ice 101® Peppermint Schnapps",
    "Ice Cream",
    "Ice Cubes",
    "Ice Milk",
    "Iced Tea",
    "Instant Coffee",
    "Instant Tea",
    "Irish Cream",
    "Irish Mist® Herbal Liqueur",
    "Irish Whiskey",
    "Italian Vermouth",
    "J & B® Scotch Whisky",
    "Jack Daniel's® Old No.7 Tennessee Whiskey",
    "Jack Daniel's® Tennessee Whiskey",
    "Jagermeister® Herbal Liqueur",
    "Jamaican Dark Rum",
    "Jameson® Irish Whiskey",
    "Jello",
    "Jim Beam Black Label Bourbon Whiskey",
    "Jim Beam® Bourbon Whiskey",
    "Jim Beam® Rye Whiskey",
    "Johnnie Walker® Black Label Scotch Whisky",
    "Johnnie Walker® Red Label Scotch Whisky",
    "Johnnie Walker® Scotch Whisky",
    "Jolt® Cola",
    "Jones® Cream Soda",
    "Jones® Green Apple Soda",
    "Jose Cuervo® 1800 Tequila",
    "Jose Cuervo® Clasico Silver Tequila",
    "Jose Cuervo® Especial Gold Tequila",
    "Jose Cuervo® Gold Tequila",
    "Jose Cuervo® Margarita Mix",
    "Jose Cuervo® White Tequila",
    "Juicy Juice® Orange Tangerine Juice",
    "Kahlua® Coffee Liqueur",
    "Kahlua® Especial Coffee Liqueur",
    "Kamchatka® Vodka",
    "Kamora® Coffee Liqueur",
    "Kazkar Feni® Cashew Apple Liqueur",
    "Ke Ke Beach® Key Lime Liqueur",
    "Ketel One® Vodka",
    "Key Lime Juice",
    "Key Lime Liqueur",
    "Kim Milk",
    "Kina® Lillet Blanc Wine",
    "Kirschwasser® Cherry Brandy",
    "Kiwi",
    "Kiwi Juice",
    "Kiwi Liqueur",
    "Kiwi Syrup",
    "Knob Creek® Bourbon Whiskey",
    "Kool-Aid®",
    "Kool-Aid® Berry Blue Mix",
    "Kool-Aid® Blue Raspberry Mix",
    "Kool-Aid® Cherry Mix",
    "Kool-Aid® Grape Mix",
    "Kool-Aid® Lemon-Lime Mix",
    "Kool-Aid® Orange Mix",
    "Kool-Aid® Strawberry Mix",
    "Kool-Aid® Tropical Punch Mix",
    "Kool-Aid® Watermelon-Cherry",
    "Koskenkorva® Vodka",
    "Kronik® Energy Drink",
    "Kummel® Caraway Liqueur",
    "La Grande Passion® Liqueur",
    "Lager",
    "Lambrusco® Red Wine",
    "Lapponia Lakka Cloudberry Liqueur",
    "Lass 7-Up® Soda",
    "Lass Beer",
    "Lass Coca-Cola®",
    "Lass Cranberry Juice",
    "Lass Ginger Ale",
    "Lass Guinness® Stout",
    "Lass Ice",
    "Lass Ice Cubes",
    "Lass Lager",
    "Lass Lemonade",
    "Lass Milk",
    "Lass Orange Juice",
    "Lass Orangina® Orange Soda",
    "Lass Pineapple Juice",
    "Lass Red Wine",
    "Lass Root Beer",
    "LBV Port",
    "Lemon",
    "Lemon Iced Tea",
    "Lemon Juice",
    "Lemon Liqueur",
    "Lemon Rum",
    "Lemon Sherbet",
    "Lemon Soda",
    "Lemon Syrup",
    "Lemon Vodka",
    "Lemon-Lime Mix",
    "Lemon-Lime Soda",
    "Lemonade",
    "Lemons",
    "Licor 43® Liqueur",
    "Light Beer",
    "Light Cream",
    "Light Rum",
    "Light Sprite® Soda",
    "Light Whipped Cream",
    "Lillet® Blanc Wine",
    "Lime",
    "Lime Cordial",
    "Lime Gin",
    "Lime Jell-O",
    "Lime Juice",
    "Lime Liqueur",
    "Lime Sherbet",
    "Lime Syrup",
    "Lime Vodka",
    "Limeade",
    "Limes",
    "Limoncello Lemon Liqueur",
    "Lipton® Brisk Iced Tea",
    "Lipton® Iced Tea",
    "London Dry Gin",
    "Loose Tea",
    "Looza® Banana Nectar",
    "Lord Calvert® Canadian Whisky",
    "Louisiana Hot Sauce",
    "Lychee Liqueur",
    "Mad Dog® Grape Wine",
    "Madeira",
    "Maker's Mark® Bourbon Whiskey",
    "Malibu® Banana Rum",
    "Malibu® Coconut Rum",
    "Malibu® Mango Rum",
    "Malibu® Passion Fruit Rum",
    "Malibu® Pineapple Rum",
    "Mandarin Juice",
    "Mandarin Liqueur",
    "Mandarine Napoleon® Orange Liqueur",
    "Mango",
    "Mango Juice",
    "Mango Liqueur",
    "Mango Nectar",
    "Mango Puree",
    "Mango Rum",
    "Mango Syrup",
    "Mangos",
    "Maple Syrup",
    "Maraschino Cherries",
    "Maraschino Cherry Juice",
    "Maraschino Liqueur",
    "Maraschino Syrup",
    "Margarita Mix",
    "Marie Brizard® Anisette Licorice Liqueur",
    "Marie Brizard® Apry Apricot Brandy",
    "Marie Brizard® Creme De Fraise Des Bois",
    "Marie Brizard® Creme De Mure",
    "Marie Brizard® Mango Passion Liqueur",
    "Marie Brizard® Peach Liqueur",
    "Marie Brizard® Poire Williams Pear Liqueur",
    "Martinelli's® Apple Cider",
    "Martini & Rossi® Bianco Vermouth",
    "Martini & Rossi® Dry Vermouth",
    "Martini & Rossi® Extra Dry Vermouth",
    "Martini & Rossi® Sweet Vermouth",
    "Maui® Blue Hawaiian Schnapps",
    "Maui® Tropical Schnapps",
    "McCormick's® Vodka",
    "McGuinness® Melon Liqueur",
    "Medium Red Wine",
    "Medium White Wine",
    "Mello Yello® Citrus Soda",
    "Melon Liqueur",
    "Melon Vodka",
    "Melted Chocolate",
    "Merlot Red Wine",
    "Metaxa Brandy",
    "Mexican Beer",
    "Mexican Hot Chocolate",
    "Mezcal",
    "MGD® Lite Lager",
    "Midori® Melon Liqueur",
    "Mike's® Hard Lemonade",
    "Milk",
    "Miller® Red Dog Lager",
    "Milo's® Sweet Tea",
    "Mineral Water",
    "Mint",
    "Mint Chocolate Ice Cream",
    "Mint Liqueur",
    "Mint Schnapps",
    "Mint Syrup",
    "Minute Maid® Fruit Punch",
    "Minute Maid® Lemonade",
    "Minute Maid® Limeade Soda",
    "Minute Maid® Orange Juice",
    "Molasses",
    "Molson® Canadian Beer",
    "Monin® Passion-Fruit Syrup",
    "Monin® Strawberry Syrup",
    "Monster® Energy Drink",
    "Moonshine Whiskey",
    "Mott's® Clamato Juice",
    "Mount Gay® Barbados Rum",
    "Mount Gay® Eclipse Barbados Rum",
    "Mountain Dew® Citrus Soda",
    "Mountain Dew® Code Red Soda",
    "Mountain Dew® Lime Soda",
    "Mountain Dew® Pitch Black Soda",
    "Mozart® Black Chocolate Liqueur",
    "Mozart® Original Chocolate Liqueur",
    "Mozart® White Chocolate Liqueur",
    "Mr & Mrs T® Sweet and Sour Mix",
    "Mudslide Mix",
    "Myer's® Dark Rum",
    "Napolean Brandy",
    "Natural® Light Lager",
    "Nestea® Iced Tea",
    "Newcastle Brown Ale® Lager",
    "Noilly Prat® French Vermouth",
    "Nonfat Milk",
    "Nutmeg",
    "Ocean Spray® Cranberry Juice",
    "Ocean Spray® Cranberry Juice Cocktail",
    "Ocean Spray® White Cranberry Juice",
    "Old Crow® Bourbon Whiskey",
    "Old Grandad® Bourbon Whiskey",
    "Old Krupnik® Honey Liqueur",
    "Olive Juice",
    "Opal Nera® Black Sambuca",
    "Orange",
    "Orange Bitters",
    "Orange Crush",
    "Orange Curacao Liqueur",
    "Orange Jell-O",
    "Orange Juice",
    "Orange Liqueur",
    "Orange Reef® Vodka",
    "Orange Rum",
    "Orange Sherbet",
    "Orange Soda",
    "Orange Vodka",
    "Orange-Pineapple Juice",
    "Orangeade",
    "Oranges",
    "Orgeat Syrup",
    "Oude Genever Gin",
    "Ouzo Anise Liqueur",
    "Ovaltine® Cocoa",
    "Overproof Rum",
    "Overproof White Rum",
    "PAMA® Pomegranate Liqueur",
    "Papaya Juice",
    "Parfait Amour® Orange Liqueur",
    "Parkling Water",
    "Passion-Fruit Juice",
    "Passion-Fruit Liqueur",
    "Passion-Fruit Nectar",
    "Passion-Fruit Puree",
    "Passion-Fruit Syrup",
    "Passoa® Liqueur",
    "Pastis Liqueur",
    "Patron® Silver Tequila",
    "Peach",
    "Peach Brandy",
    "Peach Juice",
    "Peach Liqueur",
    "Peach Nectar",
    "Peach Puree",
    "Peach Schnapps",
    "Peach Vodka",
    "Peaches",
    "Peanut Butter",
    "Pear Cider",
    "Pear Juice",
    "Pear Liqueur",
    "Pear Schnapps",
    "Pear Soda",
    "Pecher Mignon® Peach Liqueur",
    "Pepper",
    "Pepper Vodka",
    "Peppermint Liqueur",
    "Peppermint Schnapps",
    "Peppers",
    "Pepsi® Cola",
    "Pepsi® Diet",
    "Pepsi® Holiday Spice",
    "Pepsi® Slice Soda",
    "Pepsi® Vanilla Cola",
    "Pernod® Licorice Liqueur",
    "Perrier® Lemon Soda Water",
    "Perrier® Soda Water",
    "Peychaud® Bitters",
    "Phillips® Butter Ripple Schnapps",
    "Pickle Juice",
    "Pimm's® Gin",
    "Pimp® Apple Juice",
    "Pina Colada Mix",
    "Pine-Orange-Banana Juice",
    "Pineapple",
    "Pineapple Jell-O",
    "Pineapple Juice",
    "Pineapple Liqueur",
    "Pineapple Rum",
    "Pineapple Syrup",
    "Pineapple Vodka",
    "Pineapple Wine",
    "Pineapple-Coconut Juice",
    "Pineapples",
    "Pineau Des Charentes® Red Wine",
    "Pineau Des Charentes® White Wine",
    "Pink Grapefruit Juice",
    "Pink Lemonade",
    "Pisang Ambon® Liqueur",
    "Pisco Brandy",
    "Plain Yoghurt",
    "Plum Brandy",
    "Plum Wine",
    "Plymouth® Gin",
    "Polish Vodka",
    "Pomegranate Juice",
    "Pomegranate Schnapps",
    "POM® Pomegranate Juice",
    "Popov® Vodka",
    "Port",
    "Powdered Sugar",
    "Powers® Irish Whiskey",
    "Praline New Orleans-Style Pecan Liqueur",
    "Premium Tequila",
    "Prosecco® Sparkling Wine",
    "Prune Juice",
    "Punt E Mes Red Vermouth",
    "Pusser's® Dark Rum",
    "Quality Vodka",
    "Raisins",
    "Raki Liqueur",
    "Raspberries",
    "Raspberry",
    "Raspberry Cordial",
    "Raspberry Ice Cream",
    "Raspberry Juice",
    "Raspberry Lemonade",
    "Raspberry Liqueur",
    "Raspberry Puree",
    "Raspberry Schnapps",
    "Raspberry Sherbet",
    "Raspberry Soda",
    "Raspberry Sorbet",
    "Raspberry Syrup",
    "Raspberry Vodka",
    "Rebel Yell® Bourbon Whiskey",
    "Red Bull® Energy Drink",
    "Red Cinnamon Schnapps",
    "Red Grape Juice",
    "Red Hawaiian Punch®",
    "Red Jak® Energy Drink",
    "Red Orange Juice",
    "Red Soda",
    "Red Tabasco® Sauce",
    "Red Wine",
    "RedRum® Rum",
    "Reen Olive",
    "Remy Martin® Cognac",
    "Remy® Red Cognac",
    "Ribena® Blackcurrant Cordial",
    "Ricard® Pastis",
    "Rock and Rye® Liqueur",
    "Rockstar® Energy Drink",
    "Rolling Rock® Lager",
    "Romana® Black Sambuca",
    "Romana® White Sambuca",
    "Root Beer",
    "Root Beer Schnapps",
    "Rose's® Blue Raspberry Mixer",
    "Rose's® Grenadine Syrup",
    "Rose's® Lime Juice",
    "Rose's® Sour Apple Mix",
    "Rose's® Sweet and Sour Mix",
    "Rosso Vermouth",
    "Round Cardamom",
    "Round Cinnamon",
    "Royal Crown® Cola",
    "Ruby Grapefruit Juice",
    "Ruby Port",
    "Rum",
    "Rum Cream Liqueur",
    "Rum Tree® Liqueur",
    "Rumple Minze® Peppermint Liqueur",
    "Russian Vodka",
    "Rye Whiskey",
    "Safari® Liqueur",
    "Sagatiba Pura",
    "Sailor Jerry® Spiced Navy Rum",
    "Sake Rice Wine",
    "Salt",
    "Sambuca",
    "Sauternes White Wine",
    "Sauza® Conmemorativo Tequila",
    "Sauza® Hornitos Reposado Tequila",
    "Sauza® Tequila",
    "Schweppes® Bitter Lemon Soda",
    "Schweppes® Ginger Ale",
    "Schweppes® Indian Tonic Water",
    "Schweppes® Russian Tonic Water",
    "Schweppes® Tonic Water",
    "Scotch Whisky",
    "Seagram's® 7 Whisky",
    "Seagram's® Gin",
    "Seagram's® Lime Twisted Gin",
    "Sebor® Absinth Absinthe",
    "Semisweet Chocolate",
    "Sherbet",
    "Sherry",
    "Shochu",
    "Sierra Mist® Soda",
    "Silver Rum",
    "Silver Tequila",
    "Simple Syrup",
    "Single Cream",
    "Skim Milk",
    "Skyy® Blue Vodka",
    "Skyy® Citrus Vodka",
    "Skyy® Melon Vodka",
    "Skyy® Orange Vodka",
    "Skyy® Spiced Vodka",
    "Skyy® Vanilla Vodka",
    "Skyy® Vodka",
    "Sloe Gin",
    "Smirnoff® Apple Vodka",
    "Smirnoff® Black Cherry Twist Vodka",
    "Smirnoff® Black Ice",
    "Smirnoff® Blue Label Vodka",
    "Smirnoff® Citrus Twist Vodka",
    "Smirnoff® Citrus Vodka",
    "Smirnoff® Cranberry Twist Vodka",
    "Smirnoff® Green Apple Twist Vodka",
    "Smirnoff® Ice",
    "Smirnoff® Ice Triple Black",
    "Smirnoff® Lemon Vodka",
    "Smirnoff® Lime Twist Vodka",
    "Smirnoff® Orange Twist Vodka",
    "Smirnoff® Raspberry Twist Vodka",
    "Smirnoff® Raspberry Vodka",
    "Smirnoff® Red Label Vodka",
    "Smirnoff® Strawberry Twist Vodka",
    "Smirnoff® Vanilla Twist Vodka",
    "Smirnoff® Vodka",
    "Smirnoff® Watermelon Twist Vodka",
    "Smirnoff® Watermelon Vodka",
    "SmirnoffŽ No. 21 Vodka",
    "Snapple® Kiwi-Strawberry Soda",
    "Snapple® Lemonade Soda",
    "Snapple® Mango Madness Soda",
    "Snapple® Rain Soda",
    "Sobe® Adrenaline Rush Energy Drink",
    "Sobe® Energy Drink",
    "Soda",
    "Soda Water",
    "Soho® Lychee Liqueur",
    "Sour Apple Mix",
    "Sour Cherry Juice",
    "Sour Puss® Apple Liqueur",
    "Sour Puss® Raspberry Liqueur",
    "Sourz® Apple Liqueur",
    "Southern Comfort® Black Label Peach Schnapps",
    "Southern Comfort® Peach Liqueur",
    "Soy Milk",
    "Soy Sauce",
    "Soymilk",
    "Spanish Brandy",
    "Sparkling Apple Cider",
    "Sparkling Apple Juice",
    "Sparkling Bitter Lemon Soda",
    "Sparkling Water",
    "Sparkling White Wine",
    "Sparks® Energy Drink",
    "Spiced Rum",
    "Spicy Hot V8 Juice",
    "Sprite Remix",
    "Sprite® Soda",
    "Sprite® Zero Soda",
    "Squirt® Citrus Soda",
    "Starbucks® Coffee Liqueur",
    "Stella Artois® Lager",
    "Stolichnaya® Raspberry Vodka",
    "Stolichnaya® Strawberry Vodka",
    "Stolichnaya® Vanilla Vodka",
    "Stolichnaya® Vodka",
    "Stoli® Blueberi Vodka",
    "Stoli® Citros Vodka",
    "Stoli® Kafya Vodka",
    "Stoli® Limonnaya Vodka",
    "Stoli® Ohranj Vodka",
    "Stoli® Persik Vodka",
    "Stoli® Pertsovka Vodka",
    "Stoli® Razberi Vodka",
    "Stoli® Strasberi Vodka",
    "Stoli® Vanil Vodka",
    "Stoli® Zinamon Vodka",
    "Stout",
    "Strawberries",
    "Strawberry",
    "Strawberry Brandy",
    "Strawberry Daiquiri Mix",
    "Strawberry Ice Cream",
    "Strawberry Jell-O",
    "Strawberry Juice",
    "Strawberry Liqueur",
    "Strawberry Margarita Mix",
    "Strawberry Puree",
    "Strawberry Schnapps",
    "Strawberry Soda",
    "Strawberry Syrup",
    "Strawberry Vodka",
    "Strawberry Yogurt",
    "Strega® Herbal Liqueur",
    "Stroh® 80 Rum",
    "Strong Coffee",
    "Strong Tea",
    "Strong, Coffee",
    "Strongbow® Cider",
    "Sugar",
    "Sugar Syrup",
    "Sun Drop® Citrus Soda",
    "Sunkist® Orange Soda",
    "Sunny Delight® California Style Orange Juice",
    "Sunny Delight® Orange Juice",
    "Suntory® Royal Whisky",
    "Superfine Sugar",
    "Surge® Citrus Soda",
    "Swedish Punsch",
    "Sweet and Sour Mix",
    "Sweet Cream",
    "Sweet Sherry",
    "Sweet Vermouth",
    "Sweetened Condensed Milk",
    "Sweetened Iced Tea",
    "Sweetened Lemon Juice",
    "Sweetened Lime Juice",
    "Sweetener",
    "Swiss Chocolate Almond Liqueur",
    "Syrup of Roses",
    "Tabasco® Sauce",
    "Taboo®",
    "Tampico® Fruit Punch",
    "Tangerine Juice",
    "Tang® Powdered Soft Drink",
    "Tanqueray® Gin",
    "Tanqueray® Rangpur Gin",
    "Tarantula Azul Tequila",
    "Tawny Port",
    "Tea",
    "Tennessee Whiskey",
    "Tequila",
    "Tequila Rose® Strawberry Cream Liqueur",
    "Three Olives® Cherry Vodka",
    "Three Olives® Grape Vodka",
    "Three Olives® Vodka",
    "Tia Maria® Coffee Liqueur",
    "Tomato Juice",
    "Tonic Water",
    "Triple Sec",
    "Trong Tea",
    "Tropical-Fruit Schnapps",
    "Tropicana® Orange Juice",
    "Tropicana® Twister Watermelon-Strawberry Juice",
    "Truffles® Chocolate Liqueur",
    "Tuaca® Citrus Liqueur",
    "Tuborg® Lager",
    "Tullamore Dew® Irish Whiskey",
    "Turkey Hill® Iced Tea",
    "Two Fingers® Gold Tequila",
    "Unsweetened Chocolate",
    "Unsweetened Cocoa",
    "Unsweetened Orange Juice",
    "Unsweetened Pineapple",
    "Unsweetened Pineapple Juice",
    "UV® Blue Raspberry Vodka",
    "UV® Orange Vodka",
    "V8 Splash Tropical Blend",
    "V8® Vegetable Juice",
    "Van Der Hum® Liqueur",
    "Vandermint® Chocolate Mint Liqueur",
    "Vanilla",
    "Vanilla Extract",
    "Vanilla Ice Cream",
    "Vanilla Liqueur",
    "Vanilla Milk",
    "Vanilla Rum",
    "Vanilla Schnapps",
    "Vanilla Syrup",
    "Vanilla Vodka",
    "Vanilla Yoghurt",
    "Vanille Royale® Vanilla Cream Liqueur",
    "Vault® Energy Drink",
    "Vermeer® Dutch Chocolate Cream Liqueur",
    "Vermouth",
    "Vernors® Original Ginger Soda",
    "Vincent Van Gogh® Dutch Chocolate Vodka",
    "Vincent Van Gogh® Espresso Vodka",
    "Vladivar® Vodka",
    "Vodka",
    "vs Cognac",
    "VSOP Cognac",
    "Warm Milk",
    "Water",
    "Watermelon Jell-O",
    "Watermelon Liqueur",
    "Watermelon Schnapps",
    "Watermelon Vodka",
    "Weetened Condensed Milk",
    "Weetened Milk",
    "Welch's® Grape Juice",
    "Whaler's® Vanilla Rum",
    "Whipped Cream",
    "Whipped Heavy Cream",
    "Whipping Cream",
    "Whiskey",
    "Whisky",
    "Whisky Sour Mix",
    "White Brandy",
    "White Chocolate Liqueur",
    "White Cranberry Juice",
    "White Creme De Cacao",
    "White Creme De Menthe",
    "White Curacao Liqueur",
    "White Grape Juice",
    "White Lightning® Cider",
    "White Pepper",
    "White Port",
    "White Rum",
    "White Sambuca",
    "White Sugar",
    "White Tequila",
    "White Wine",
    "Whole Milk",
    "Wild Spirit® Chocolate Raspberry Liqueur",
    "Wild Turkey® 101 Bourbon Whiskey",
    "Wild Turkey® Bourbon Whiskey",
    "Wildberry Schnapps",
    "Windsor® Canadian Whisky",
    "WKD® Original Vodka Blue",
    "Worcestershire Sauce",
    "Wyborowa® Vodka",
    "X-Rated Fusion® Liqueur",
    "Yellow Chartreuse®",
    "Yellow Lemonade",
    "Yoghurt",
    "Yoo-Hoo® Chocolate Milk",
    "Yukon Jack® Canadian Whisky",
    "Zen® Green Tea Liqueur",
    "Zima",
    "Zinfandel® White Wine",
    "Zubrowka® Vodka"];